In [27]:
import torch
from torch import Tensor

In [28]:
print("torch version", torch.__version__)

torch version 2.3.0+cu121


In [29]:
torch.manual_seed(303)

In [30]:
# creating a new tensor with dimensions (2, 3, 4).
# tensor has three dimensions: 2, 3, and 4.
x = Tensor(2, 3, 4)
print(x)

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 1.4013e-45,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  1.4013e-44,  0.0000e+00],
         [ 1.4013e-45,  0.0000e+00, -1.7014e+38,  1.1515e-40]]])


In [31]:
# creating a tensor from a list of provided values.
x = Tensor([[1, 2], [3, 4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [32]:
# creating a new tensor with dimensions (2, 3, 4) using the torch.rand function. 
# this tensor is filled with random numbers in the range [0, 1].
x = torch.rand(2, 3, 4)
print(x)

tensor([[[0.0380, 0.1307, 0.9450, 0.1469],
         [0.0033, 0.1187, 0.5883, 0.8929],
         [0.0203, 0.3851, 0.4325, 0.0792]],

        [[0.8804, 0.1749, 0.2369, 0.6554],
         [0.8336, 0.7172, 0.4542, 0.6316],
         [0.7780, 0.3755, 0.2328, 0.7657]]])


In [33]:
# retrieve the dimensions of tensor x using the shape property
shape = x.shape
print("tensor dim:", x.shape)

tensor dim: torch.Size([2, 3, 4])


In [34]:
size = x.size()
print("tensor dim:", size)

tensor dim: torch.Size([2, 3, 4])


In [35]:
dim1, dim2, dim3 = x.size()
print("tensor dim:", dim1, dim2, dim3)

tensor dim: 2 3 4


In [36]:
import numpy as np

# Numpy array
np_arr = np.array([[1, 2], [3, 4]])
# Converting from NumPy to PyTorch.
tensor = torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)

Numpy array: [[1 2]
 [3 4]]
PyTorch tensor: tensor([[1, 2],
        [3, 4]])


In [37]:
tensor = torch.arange(4)
np_arr = tensor.numpy()

print("PyTorch tensor:", tensor)
print("Numpy array:", np_arr)

PyTorch tensor: tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]


In [38]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
y = x1 + x2

print("X1", x1)
print("X2", x2)
print("Y", y)

X1 tensor([[0.1480, 0.8440, 0.6702],
        [0.3148, 0.2298, 0.5666]])
X2 tensor([[0.6896, 0.2062, 0.9707],
        [0.0466, 0.2240, 0.4959]])
Y tensor([[0.8377, 1.0502, 1.6409],
        [0.3614, 0.4538, 1.0625]])


In [39]:
# function generates a sequence of numbers from 0 to 5 (6 elements)
x = torch.arange(6)
print("X", x)

X tensor([0, 1, 2, 3, 4, 5])


In [40]:
# reshaping tensor x from (6,) to (2, 3) using the .view() method.
x = x.view(2, 3)
print("X", x)

X tensor([[0, 1, 2],
        [3, 4, 5]])


In [41]:
x = torch.arange(12).view(3, 4)
print("X", x)

X tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [42]:
# second column
print(x[:, 1])

tensor([1, 5, 9])


In [43]:
# first row
print(x[0])

tensor([0, 1, 2, 3])


In [44]:
# first two rows, last column
print(x[:2, -1])

tensor([3, 7])


Excercises

In [45]:
# Creating Tensors
# a) Create a tensor filled with zeros of size (5, 3)
zerowy = torch.zeros((5, 3))
print(zerowy)

# b) Create a tensor filled with ones of any size you choose
jedynkowy = torch.ones((4, 5))
print(jedynkowy)

# c) Create a tensor filled with a sequence of integers from 10 to 19.
sekwencyjny = torch.arange(10, 20)
print(sekwencyjny)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


In [46]:
# Tensor Operations
# a) Add two tensors of the same shape and print the result.
tensor1 = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor2 = torch.tensor([[7, 8], [9, 10], [11, 12]])
tensor_dodawanie = tensor1 + tensor2
print(tensor_dodawanie)
# b) Multiply two tensors of compatible sizes using element-wise multiplication.
tensor_mnożenie = tensor1 * tensor2
print(tensor_mnożenie)
# c) Calculate the mean and sum of the elements in the tensor.
tensor_dodawanie = tensor.to(torch.float)
tensor_srednia = torch.mean(tensor_dodawanie)
print(tensor_srednia)
tensor_suma = torch.sum(tensor_dodawanie)
print(tensor_suma)

tensor([[ 8, 10],
        [12, 14],
        [16, 18]])
tensor([[ 7, 16],
        [27, 40],
        [55, 72]])
tensor(1.5000)
tensor(6.)


In [47]:
# Reshaping Tensors
# a) Reshape one of the previously created tensors into the shape (3, 5).
tensor_view = tensor1.view(2,3)
print(tensor_view)
# b) Flatten a tensor of any shape into a one-dimensional tensor and print its contents.
tensor_splaszczony = tensor1.view(-1)
print(tensor_splaszczony)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([1, 2, 3, 4, 5, 6])


In [48]:
# Indexing and Slicing Tensors
# a) Select the elements lying on the diagonal of a square matrix tensor.
tensor_kwadratowy = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
przekatna = torch.diagonal(tensor_kwadratowy)
print(przekatna)

# b) Extract the second row from a tensor of shape (3, 4).
tensor_3x4 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
drugi_wiersz = tensor_3x4[1]
print(drugi_wiersz)

# c) Create a tensor of shape (4, 4), then extract the elements located in even columns and odd rows.
tensor_4x4 = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
wynik = tensor_4x4[::2, 1::2]
print(tensor_4x4)
print(wynik)

tensor([1, 5, 9])
tensor([5, 6, 7, 8])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
tensor([[ 2,  4],
        [10, 12]])


In [49]:
# Tensor and Numpy Operations
# a) Create a tensor from a Python list and convert it to a Numpy array.
lista = [1, 2, 3, 4, 5]
tensor3 = torch.tensor(lista)
numpy_tablica = tensor3.numpy()
print(tensor3)
print(numpy_tablica)
# b) Change the data type of the tensor from float to int and explain the observed changes.
tensor3 = tensor.to(torch.float)
print(tensor3)

tensor([1, 2, 3, 4, 5])
[1 2 3 4 5]
tensor([0., 1., 2., 3.])


In [50]:
# Matrix Operations
# a) Calculate the dot product of two tensors with appropriate sizes.
tensor4 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor5 = torch.tensor([[7, 8], [9, 10], [11, 12]])
iloczyn_macierzowy = torch.mm(tensor4, tensor5)
print(iloczyn_macierzowy)
# b) Transpose the tensor and explain how its shape changes.
tensor_transponowany = iloczyn_macierzowy.t()
print(tensor_transponowany)

tensor([[ 58,  64],
        [139, 154]])
tensor([[ 58, 139],
        [ 64, 154]])


In [51]:
# Advanced Indexing
# a) Use a logical mask to select from the tensor only those elements that are greater than the mean value of all elements in the tensor.
tensor6 = torch.arange(1, 20)
tensor6_float = tensor6.to(torch.float)
srednia = torch.mean(tensor6_float)
print(f"tensora mean -> {srednia}")

maska_logiczna = tensor6_float > srednia
wybrane_elementy = tensor6[maska_logiczna]
print(wybrane_elementy)

# b) Select the elements from the tensor that are even and replace them with the value -1.
maska_parzyste = tensor6 % 2 == 0
tensor6[maska_parzyste] = -1
print(tensor6)

tensora mean -> 10.0
tensor([11, 12, 13, 14, 15, 16, 17, 18, 19])
tensor([ 1, -1,  3, -1,  5, -1,  7, -1,  9, -1, 11, -1, 13, -1, 15, -1, 17, -1,
        19])


In [52]:
# Task 8: In-Place Operations
# a) Perform any in-place arithmetic operation (e.g., addition) and observe how the original tensor changes.
print(f"Origin -> {tensor6}")
w_miejscu = tensor6.add_(4)
print(w_miejscu)


Origin -> tensor([ 1, -1,  3, -1,  5, -1,  7, -1,  9, -1, 11, -1, 13, -1, 15, -1, 17, -1,
        19])
tensor([ 5,  3,  7,  3,  9,  3, 11,  3, 13,  3, 15,  3, 17,  3, 19,  3, 21,  3,
        23])
